### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tamzinselvi** [magical/pokemon-sprites-rby#1]
Hi @magical -- was about to whip my own R/B sprite interpreter when I noticed your awesome repository! 👍 

I'd like to use your code for an open source side project, would you mind including a license?  Let me know and thank you for all your fantastic work on this.

**Comment by magical** [comment]
Sure thing. Thanks for reminding me; I often forget to include a license in my projects — especially things like this that very few people will be interested in. I've added a license (BSD): https://github.com/magical/pokemon-sprites-rby/blob/master/LICENSE.

Good luck on your project.

**Comment by tamzinselvi** [comment]
Much appreciated, thank you again for all your great work!
